name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: dist/github-contribution-grid-snake.svg
